### ISSUE TITLE
[PE-D][Tester D] Help command not functional

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W15-1/tp#163]
typing `help` and pressing enter does not submit the command or display any feedback

typing `help add` or any other instruction in the `help [command]` format returns invalid command format, without instructions of how to use the command

parameter description also seems to be incorrect, returning  `[command] (must be a valid command) help [command]`

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: juzzztinsoong/ped#2

**Comment by eyelessrhyme7** [comment]
Help seems to work in the Java Code but not in the build. Thank you for pointing it out!
