### ISSUE TITLE
[PE-D][Tester D] Tasks not appearing in the Task Table UI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W15-1/tp#178]
Adding a task with the command `add n/Grade task p/1 t/assignment t/grade d/01-12-2023 l/www.example.com` causes it to appear in the priority 1 urgency 5 cell,
then adding a task with the command `add n/Grade assignments p/1 t/assignment t/grade d/01-01-2023 l/www.example.com` causes the previous task to vanish from its cell. Task is not visible anywhere in the task table ui.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: juzzztinsoong/ped#5

**Comment by eyelessrhyme7** [comment]
Unable to reproduce issue. We have added some fixes to the matrix, so this isolated issues might be solved
