### ISSUE TITLE
[PE-D][Tester E] Error output message for `delete` command missing puncutation

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W15-1/tp#181]
![image.png](https://raw.githubusercontent.com/vansh284/ped/main/files/2ef00400-40e9-4237-a994-ab4c17760e63.png)

There is a missing full stop and space in the last line in the screenshot above.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: vansh284/ped#5

**Comment by eyelessrhyme7** [comment]
Thank you for pointing out! Fixed in latest. There should be an enter after IRREVERSIBLE
