### ISSUE TITLE
[PE-D][Tester B] Filter for Recurring Tasks not Listing the Weekly Tasks 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W15-1/tp#208]
![Screenshot 2023-11-03 at 5.18.24 PM.png](https://raw.githubusercontent.com/butteredyakiimo/ped/main/files/d2dc304c-dd5c-4f93-9512-c3aaa1c98466.png)
Tasks 2 and 4 are tagged weekly

![Screenshot 2023-11-03 at 5.17.09 PM.png](https://raw.githubusercontent.com/butteredyakiimo/ped/main/files/03872ef9-1c6b-4ef5-895e-8475b3dcf408.png)
Entered this command

![Screenshot 2023-11-03 at 5.17.22 PM.png](https://raw.githubusercontent.com/butteredyakiimo/ped/main/files/25bc2af4-1efa-4507-913d-99f896926fb0.png)
but nothing is showing :(. May want to look into that!

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: butteredyakiimo/ped#11

**Comment by eyelessrhyme7** [comment]
Need to specify Recur Tag is different from normal tag.
